### ISSUE TITLE
can't running NEI from vim

### ISSUE THREAD

**Issue by vaaaaanquish** [pyviz/nei#6]
Hi. Thank you for starting great repo.

I have two issues. I couldn't run nei from `vim`. 

### tornado RuntimeError    

I caught the following RuntimeError.
```
:NEI
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "nei/vim/vim_nei.py", line 63, in nei_connect_to_server
    client = Client("ws://localhost:9995")
  File "nei/vim/vim_nei.py", line 36, in __init__
    self.ioloop.start()
  File "~/.pyenv/versions/3.6.8/lib/python3.6/site-packages/tornado/platform/asyncio.py",
 line 148, in start
    self.asyncio_loop.run_forever()
  File "~/.pyenv/versions/3.6.8/lib/python3.6/asyncio/base_events.py", line 425, in run_f
orever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```
```
(logging)
INFO:root:STARTED: Server started and listening
INFO:tornado.access:101 GET / (127.0.0.1) 3.35ms
INFO:root:Connection opened
INFO:root:Added editor client connection
INFO:root:ON_CLOSE
```
This is similar to the following issue. I tried the solution shown here.
https://github.com/jupyter/notebook/issues/3397
```
pip3 install tornado==4.5.3
```

### cann't see the result

After solving tornado RuntimeError, I was able to get `:python3 view_browser()` to work properly, but I couldn't see result on firefox when I use `:python3 run_these_lines()`. 
I look at log using [echo function](https://github.com/pyviz/nei/blob/master/vim/vim_nei.py#L85) , it seems that NEI can read the text of vim.

Is there a way to check if `nei.vim` works properly?

**Comment by jlstevens** [comment]
Thanks for your interest in NEI! Currently the vim support is at the prototype stage (although I know there is interest in it @esc )

One thing I realized after prototyping this is that I should probably put the tornado event loop into the background which may or may not be related to the initial issue you saw. You said that `view_browser` can work which means the server is running - when you try `run_these_lines`, do you see any logging output in the terminal where the server is running?
